import type { ChildStageCode } from "@prisma/client";

export type CategorySeed = {
  code: string;
  name: string;
  iconName: string;
  displayOrder: number;
};

export type ItemTemplateSeed = {
  code: string;
  name: string;
  categoryCode: string;
  necessityLevel: "essential" | "convenience" | "optional";
  timingLabel: string;
  priceMinKrw: number | null;
  priceMaxKrw: number | null;
  reasonText: string;
  skipReasonText: string | null;
  usedSecondhandOk: boolean;
  safetyNote: string | null;
  medicalDisclaimerRequired: boolean;
  displayOrder: number;
  active: boolean;
  stageCodes: ChildStageCode[];
};

export type ProductLinkSeed = {
  itemTemplateCode: string;
  platform: "coupang" | "naver" | "custom";
  title: string;
  url: string;
  affiliateUrl: string | null;
  affiliatePartnerCode: string | null;
  isAffiliate: boolean;
  isSponsored: boolean;
  sponsorLabel: string | null;
  priceSnapshotKrw: number | null;
  displayOrder: number;
  active: boolean;
  disclosureText: string | null;
};

export type DisclosureSeed = {
  key: string;
  text: string;
};

export type MobileCategoryAliasSeed = {
  /**
   * Fixed id, matched byte-for-byte against apps/mobile/src/categories.ts'
   * `categoryCatalog` entries. The mobile quick-expense tiles hardcode these UUID
   * literals client-side rather than fetching a canonical id from the server (see
   * that file's comments), so `POST /children/:childId/expenses` from the mobile
   * app always carries one of these exact ids. Round 4 adds server-side validation
   * that `categoryId` must reference an existing `categories` row; without seeding
   * these exact ids too, every mobile-originated expense would 400. These are kept
   * separate from `categorySeeds` (the locked 12) since two mobile tiles
   * intentionally share one taxonomy code ("분유/유제품" and "식비" both map to
   * `feeding_babyfood`), which the unique-per-code canonical list can't represent.
   */
  id: string;
  code: string;
  name: string;
  iconName: string;
  displayOrder: number;
  /**
   * CAT-124: always `false` for these bundles. The rows must keep existing (expenses are
   * already stored under these ids, and the 8-tile quick input + offline resend keep writing
   * them), but they must not be OFFERED as choices — they duplicate the canonical 12 under a
   * different name ("기저귀" vs "기저귀/위생"), which is exactly what a client-side same-name
   * dedupe could not fix. `GET /categories` hides them unless `?includeAll=1`.
   * Migration: prisma/migrations/000018_categories_selectable.
   */
  selectable: false;
};

export const categorySeeds: CategorySeed[] = [
  { code: "pregnancy_mother", name: "임신/산모", iconName: "mother", displayOrder: 10 },
  { code: "hospital_checkup", name: "병원/검사", iconName: "hospital", displayOrder: 20 },
  { code: "birth_postpartum", name: "출산/조리원", iconName: "birth", displayOrder: 30 },
  { code: "diaper_hygiene", name: "기저귀/위생", iconName: "diaper", displayOrder: 40 },
  { code: "feeding_babyfood", name: "수유/이유식", iconName: "bottle", displayOrder: 50 },
  { code: "clothes_laundry", name: "의류/세탁", iconName: "clothes", displayOrder: 60 },
  { code: "sleep_furniture", name: "수면/가구", iconName: "bed", displayOrder: 70 },
  { code: "outing_mobility", name: "외출/이동", iconName: "stroller", displayOrder: 80 },
  { code: "toys_books", name: "장난감/책", iconName: "book", displayOrder: 90 },
  { code: "care_education", name: "돌봄/교육", iconName: "education", displayOrder: 100 },
  { code: "insurance_savings", name: "보험/저축", iconName: "shield", displayOrder: 110 },
  { code: "etc", name: "기타", iconName: "more", displayOrder: 999 }
];

export const itemTemplateSeeds: ItemTemplateSeed[] = [
  {
    code: "pregnancy_vitamin",
    name: "임산부 영양제",
    categoryCode: "pregnancy_mother",
    necessityLevel: "essential",
    timingLabel: "임신 초기부터",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "산모가 매달 챙기는 지출을 아이 준비 기록과 함께 남길 수 있어요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "복용 여부와 종류는 담당 의료진 안내를 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 10,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "car_seat",
    name: "카시트",
    categoryCode: "outing_mobility",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 150000,
    priceMaxKrw: 700000,
    reasonText: "차량 이동이 있다면 퇴원과 외출 전에 안전 준비 상태를 확인해야 해요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "안전 인증과 설치 상태를 확인하고 사고 이력이 있는 중고 제품은 피해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 20,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "diaper_stock",
    name: "기저귀 첫 준비",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "출산 직전~0개월",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "출산 직후 반복 구매가 시작되는 기본 소모품이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 30,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "baby_bath",
    name: "아기 욕조",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "초기 목욕 시간을 안정적으로 만들 수 있는 편의 준비템이에요.",
    skipReasonText: "세면대나 큰 대야를 안전하게 쓸 수 있다면 바로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "물 사용 중에는 아이 곁을 떠나지 않아요.",
    medicalDisclaimerRequired: false,
    displayOrder: 40,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3", "infant_4_6"]
  },
  {
    code: "stroller",
    name: "유모차",
    categoryCode: "outing_mobility",
    necessityLevel: "optional",
    timingLabel: "외출이 늘어날 때",
    priceMinKrw: 100000,
    priceMaxKrw: 1200000,
    reasonText: "생활 반경과 이동 방식에 따라 외출 부담을 줄여주는 선택 준비템이에요.",
    skipReasonText: "차량 이동이 적거나 아기띠로 충분한 시기라면 구매를 늦춰도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "프레임 잠금, 브레이크, 안전벨트 상태를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 50,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "baby_food_maker",
    name: "이유식 조리 도구",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "4~6개월 전후",
    priceMinKrw: 20000,
    priceMaxKrw: 200000,
    reasonText: "이유식 시작 시 조리와 보관 흐름을 편하게 만드는 준비템이에요.",
    skipReasonText: "집에 있는 조리 도구와 보관 용기로 충분하면 별도 구매하지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "소독과 세척이 쉬운 구조인지 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 60,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "first_books",
    name: "첫 그림책",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "7~12개월",
    priceMinKrw: 10000,
    priceMaxKrw: 150000,
    reasonText: "놀이와 책 읽기 기록을 남기고 싶을 때 준비할 수 있어요.",
    skipReasonText: "도서관, 물려받은 책, 선물 책이 충분하면 새로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "찢어진 모서리나 작은 부품이 없는지 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 70,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "maternity_underwear",
    name: "임산부 속옷",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "임신 초기~중기",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "체형 변화에 맞춰 편안하게 입을 수 있는 임산부 전용 속옷이에요.",
    skipReasonText: "기존 속옷을 늘려 입거나 여유 있는 제품으로 버틸 수 있다면 바로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 80,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid"]
  },
  {
    code: "anti_nausea_relief",
    name: "입덧 완화 식품",
    categoryCode: "pregnancy_mother",
    necessityLevel: "convenience",
    timingLabel: "임신 초기",
    priceMinKrw: 8000,
    priceMaxKrw: 40000,
    reasonText: "입덧이 심한 시기에 식사를 대신하거나 도와줄 수 있는 완화 식품이에요.",
    skipReasonText: "입덧 증상이 가볍다면 별도로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "증상이 심하면 자가 대처보다 담당 의료진 상담을 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 90,
    active: true,
    stageCodes: ["pregnancy_early"]
  },
  {
    code: "pregnancy_diary",
    name: "태교 일기장",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "임신 초기~중기",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "태교 과정과 감정을 기록하고 싶을 때 준비하는 선택 준비템이에요.",
    skipReasonText: "메모 앱이나 다른 기록 방법으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 100,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid"]
  },
  {
    code: "maternity_clothes",
    name: "임부복",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "배가 불러오는 시기에 활동과 일상을 편하게 만들어주는 필수 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 110,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "body_pillow",
    name: "임산부 바디필로우",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "배가 무거워지는 시기에 수면 자세를 편하게 잡아주는 편의 준비템이에요.",
    skipReasonText: "기존 베개나 쿠션으로 자세가 편하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 120,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "stretch_care_cream",
    name: "튼살 크림",
    categoryCode: "pregnancy_mother",
    necessityLevel: "optional",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "튼살 관리를 원할 때 선택적으로 사용하는 관리 제품이에요.",
    skipReasonText: "피부 관리가 필수는 아니므로 사용하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 130,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "iron_supplement",
    name: "철분제",
    categoryCode: "pregnancy_mother",
    necessityLevel: "essential",
    timingLabel: "임신 초기~후기",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "빈혈 관리를 위해 임신 중 챙기는 필수 영양제예요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "복용 여부와 용량은 담당 의료진 안내를 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 140,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "prenatal_class",
    name: "출산 준비 교실",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 0,
    priceMaxKrw: 200000,
    reasonText: "출산과 육아를 미리 준비하고 싶을 때 참여하는 선택 교육 프로그램이에요.",
    skipReasonText: "다른 경로로 정보를 충분히 얻고 있다면 참여하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 150,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "hospital_bag",
    name: "출산 가방 준비",
    categoryCode: "birth_postpartum",
    necessityLevel: "essential",
    timingLabel: "임신 후기·출산 전",
    priceMinKrw: 50000,
    priceMaxKrw: 200000,
    reasonText: "입원과 퇴원까지 필요한 물품을 미리 챙기는 필수 준비 과정이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 160,
    active: true,
    stageCodes: ["pregnancy_late"]
  },
  {
    code: "newborn_clothes_set",
    name: "배냇저고리 세트",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "신생아가 퇴원 후 바로 입을 수 있는 필수 첫 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 170,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "feeding_bottle_set",
    name: "젖병/소독 세트",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "수유를 시작하기 전 젖병과 소독 도구를 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "소독 상태를 꾸준히 확인하고 위생을 관리해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 180,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "breast_pump",
    name: "유축기",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 50000,
    priceMaxKrw: 400000,
    reasonText: "직접 수유가 어려운 상황에서 모유를 보관하고 수유를 돕는 편의 준비템이에요.",
    skipReasonText: "직접 수유로 충분하거나 병원·조리원 대여로 해결된다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 190,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "nursing_pads",
    name: "수유 패드/산모 패드",
    categoryCode: "birth_postpartum",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "출산 후 분비물과 모유 흡수를 관리하는 필수 위생 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 200,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "crib",
    name: "아기 침대/요람",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 100000,
    priceMaxKrw: 600000,
    reasonText: "아이가 안전하게 잠들 수 있는 독립된 수면 공간을 마련하는 편의 준비템이에요.",
    skipReasonText: "부모와 함께 자는 방식으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "중고 제품이라면 안전 인증 여부와 부품 파손 여부를 꼭 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 210,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "wipes_bulk",
    name: "물티슈 대량 구매",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "0~12개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "매일 반복해서 사용하는 필수 소모품이라 미리 대량으로 준비하면 편해요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 220,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "formula",
    name: "분유",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "0~6개월",
    priceMinKrw: 25000,
    priceMaxKrw: 120000,
    reasonText: "모유 수유를 보완하거나 대체할 때 필요한 필수 먹거리예요.",
    skipReasonText: "완전 모유 수유를 하고 있다면 따로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "아이 상태에 따른 분유 선택은 담당 의료진과 상담 후 결정해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 230,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6"]
  },
  {
    code: "swaddle",
    name: "속싸개/겉싸개",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "0~3개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "신생아를 안정적으로 감싸 체온과 안정감을 지켜주는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 240,
    active: true,
    stageCodes: ["newborn_0_3"]
  },
  {
    code: "baby_thermometer",
    name: "체온계",
    categoryCode: "hospital_checkup",
    necessityLevel: "essential",
    timingLabel: "0~24개월",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "발열 여부를 빠르게 확인할 수 있는 필수 건강 관리 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 250,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "baby_detergent",
    name: "유아 세제",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "0~12개월",
    priceMinKrw: 8000,
    priceMaxKrw: 30000,
    reasonText: "아기 피부에 순한 성분으로 세탁을 관리하는 편의 준비템이에요.",
    skipReasonText: "순한 성분의 기존 세제로 충분하면 따로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 260,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "baby_skincare",
    name: "아기 로션/보습",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "0~24개월",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "건조하기 쉬운 아기 피부를 보습하는 편의 준비템이에요.",
    skipReasonText: "피부 상태가 양호하다면 매일 사용하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 270,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "nail_care_set",
    name: "아기 손톱 관리 세트",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "0~3개월",
    priceMinKrw: 5000,
    priceMaxKrw: 20000,
    reasonText: "빨리 자라는 아기 손톱을 안전하게 정리하는 편의 준비템이에요.",
    skipReasonText: "가위나 다른 도구로 관리가 가능하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "잠든 시간을 활용하고 끝이 뭉툭한 전용 도구를 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 280,
    active: true,
    stageCodes: ["newborn_0_3"]
  },
  {
    code: "baby_carrier",
    name: "아기띠",
    categoryCode: "outing_mobility",
    necessityLevel: "convenience",
    timingLabel: "0~12개월",
    priceMinKrw: 50000,
    priceMaxKrw: 250000,
    reasonText: "두 손이 자유로운 외출과 이동을 돕는 편의 준비템이에요.",
    skipReasonText: "유모차 이동으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "체중 범위와 착용 방법을 확인하고 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 290,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "mobile_toy",
    name: "모빌/백색소음기",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "0~6개월",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "시각 자극과 안정적인 수면 환경을 돕는 선택 준비템이에요.",
    skipReasonText: "다른 방법으로 아이가 잘 안정된다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 300,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6"]
  },
  {
    code: "high_chair",
    name: "아기 식탁의자",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "이유식과 식사 시간을 안정적으로 만들어주는 편의 준비템이에요.",
    skipReasonText: "안고 먹이거나 다른 좌석으로 대체할 수 있다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "안전벨트와 잠금장치 상태를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 310,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "weaning_tableware",
    name: "이유식 식기/스푼",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "4~12개월",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "이유식을 시작할 때 필요한 필수 식사 도구예요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 320,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "teether",
    name: "치발기",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "4~12개월",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "잇몸이 간지러운 시기에 아이를 달래주는 편의 준비템이에요.",
    skipReasonText: "다른 방법으로 아이가 편안해한다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "입에 넣는 제품이므로 소독 상태를 꾸준히 관리해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 330,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "play_mat",
    name: "놀이매트",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "바닥 놀이와 안전한 활동 공간을 마련하는 편의 준비템이에요.",
    skipReasonText: "기존 바닥 환경이 안전하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 340,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "safety_gate",
    name: "안전문/안전가드",
    categoryCode: "sleep_furniture",
    necessityLevel: "essential",
    timingLabel: "12~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "이동이 활발해지는 시기에 위험 구역을 막아주는 필수 안전 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: "중고 제품이라면 잠금장치와 고정 상태를 꼭 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 350,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "corner_guards",
    name: "모서리/콘센트 보호",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "12~24개월",
    priceMinKrw: 5000,
    priceMaxKrw: 30000,
    reasonText: "기어다니고 걷기 시작하는 시기에 부딪힘을 줄여주는 편의 준비템이에요.",
    skipReasonText: "가구 배치로 위험을 줄일 수 있다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 360,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "push_walker",
    name: "걸음마 보조 장난감",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "12~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "걸음마를 연습하는 시기에 흥미를 더해주는 선택 준비템이에요.",
    skipReasonText: "손을 잡아주거나 다른 방식으로 연습해도 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "바퀴 잠금과 계단 근처 사용 여부를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 370,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "first_shoes",
    name: "첫 걸음마 신발",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "12~24개월",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "걷기 시작하는 시기에 발을 보호해주는 편의 준비템이에요.",
    skipReasonText: "실내 위주 생활이라면 양말이나 실내화로 대체해도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 380,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "snack_container",
    name: "간식 용기/빨대컵",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "12~24개월",
    priceMinKrw: 5000,
    priceMaxKrw: 30000,
    reasonText: "외출 시 간식과 음료를 편리하게 챙길 수 있는 준비템이에요.",
    skipReasonText: "기존 그릇이나 컵으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 390,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "potty_trainer",
    name: "유아 변기",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "12~24개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "배변 훈련을 시작할 때 필요한 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 400,
    active: true,
    stageCodes: ["toddler_1_3"]
  },
  {
    code: "toddler_dental",
    name: "유아 칫솔/치약",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "24개월 이후",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "유치가 나기 시작하며 필요한 필수 구강 관리 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 410,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "toddler_tableware",
    name: "유아 식기 세트",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "24개월 이후",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "혼자 먹는 연습을 시작할 때 편리한 식사 준비템이에요.",
    skipReasonText: "기존 식기로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 420,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "ride_on_car",
    name: "붕붕카",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "12~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "실내외에서 활동적으로 놀 수 있게 해주는 선택 준비템이에요.",
    skipReasonText: "다른 놀이로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 430,
    active: true,
    stageCodes: ["toddler_1_3"]
  },
  {
    code: "sticker_books",
    name: "스티커북/놀이책",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "24개월 이후",
    priceMinKrw: 8000,
    priceMaxKrw: 60000,
    reasonText: "집중력과 소근육 발달을 돕는 편의 놀이 준비템이에요.",
    skipReasonText: "도서관이나 기존 놀이책으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 440,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "daycare_kit",
    name: "어린이집 준비물",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "24개월 이후",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "어린이집 등원 시 필요한 개인 물품을 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 450,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "toddler_rain_gear",
    name: "유아 우비/장화",
    categoryCode: "clothes_laundry",
    necessityLevel: "optional",
    timingLabel: "24개월 이후",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "비 오는 날 외출과 물놀이를 즐길 수 있게 해주는 선택 준비템이에요.",
    skipReasonText: "비 오는 날 외출이 적다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 460,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "kids_scooter",
    name: "킥보드와 보호장비",
    categoryCode: "outing_mobility",
    necessityLevel: "convenience",
    timingLabel: "4~7세~초등",
    priceMinKrw: 40000,
    priceMaxKrw: 200000,
    reasonText: "야외 활동 범위가 넓어지는 시기에 즐길 수 있는 편의 준비템이에요.",
    skipReasonText: "다른 야외 활동으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "헬멧과 무릎·손목 보호대를 함께 착용하고 안전한 장소에서 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 470,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "learning_desk",
    name: "유아 책상·의자",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "4~7세",
    priceMinKrw: 80000,
    priceMaxKrw: 400000,
    reasonText: "앉아서 집중하는 습관을 만들어주는 편의 준비템이에요.",
    skipReasonText: "거실 책상이나 기존 가구로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 480,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "hangul_learning",
    name: "한글/숫자 교구",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "4~7세",
    priceMinKrw: 15000,
    priceMaxKrw: 150000,
    reasonText: "한글과 숫자에 관심을 갖기 시작할 때 활용하는 선택 교육 준비템이에요.",
    skipReasonText: "다른 놀이나 기관 학습으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 490,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "art_supplies",
    name: "미술놀이 세트",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "4~7세~초등",
    priceMinKrw: 10000,
    priceMaxKrw: 60000,
    reasonText: "그리기와 만들기 놀이를 즐길 수 있게 해주는 편의 준비템이에요.",
    skipReasonText: "기관에서 재료를 제공한다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 500,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "kindergarten_kit",
    name: "유치원 입학 준비물",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "4~7세",
    priceMinKrw: 50000,
    priceMaxKrw: 200000,
    reasonText: "유치원 입학 시 필요한 개인 물품을 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 510,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "kids_bicycle",
    name: "네발 자전거와 헬멧",
    categoryCode: "outing_mobility",
    necessityLevel: "optional",
    timingLabel: "4~7세~초등",
    priceMinKrw: 80000,
    priceMaxKrw: 350000,
    reasonText: "자전거 타기를 배우기 시작할 때 활용하는 선택 준비템이에요.",
    skipReasonText: "아직 관심이 없거나 다른 놀이로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "헬멧은 머리 크기에 맞는 제품을 새로 준비하고 반드시 착용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 520,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "school_bag",
    name: "초등 책가방",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "초등학생 시기",
    priceMinKrw: 40000,
    priceMaxKrw: 250000,
    reasonText: "초등학교 입학과 함께 매일 사용하는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 530,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "school_supplies",
    name: "학용품 세트",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "초등학생 시기",
    priceMinKrw: 20000,
    priceMaxKrw: 100000,
    reasonText: "학교 수업에 필요한 필수 학용품을 갖추는 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 540,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "study_desk_lamp",
    name: "학습 책상/스탠드",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "초등~중등",
    priceMinKrw: 100000,
    priceMaxKrw: 500000,
    reasonText: "본격적인 학습 습관을 만들어주는 편의 준비템이에요.",
    skipReasonText: "기존 책상과 조명으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 550,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "kids_watch_phone",
    name: "키즈폰/스마트워치",
    categoryCode: "etc",
    necessityLevel: "convenience",
    timingLabel: "초등학생 시기",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "등하교 안전과 연락을 위해 준비하는 편의 준비템이에요.",
    skipReasonText: "다른 연락 수단으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 560,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "workbook_set",
    name: "문제집/학습지",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "초등~중등",
    priceMinKrw: 10000,
    priceMaxKrw: 80000,
    reasonText: "학습 내용을 복습하고 보충하고 싶을 때 활용하는 선택 준비템이에요.",
    skipReasonText: "학교 학습만으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 570,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "sports_equipment",
    name: "운동용품",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "초등~중등",
    priceMinKrw: 10000,
    priceMaxKrw: 100000,
    reasonText: "체육 활동이나 취미 운동을 시작할 때 활용하는 선택 준비템이에요.",
    skipReasonText: "학교 비품이나 기존 장비로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 580,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "school_uniform",
    name: "교복",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "중학생 시기",
    priceMinKrw: 150000,
    priceMaxKrw: 500000,
    reasonText: "중학교 입학과 함께 필수로 갖춰야 하는 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 590,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "study_tablet",
    name: "인강용 태블릿",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "중학생 시기",
    priceMinKrw: 300000,
    priceMaxKrw: 900000,
    reasonText: "온라인 강의 수강 환경을 갖추는 편의 준비템이에요.",
    skipReasonText: "기존 컴퓨터나 다른 기기로 수강이 가능하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 600,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "reference_books",
    name: "참고서 세트",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "중학생 시기",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "교과 학습을 보충하기 위한 필수 참고서예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 610,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "ergonomic_chair",
    name: "학습 의자",
    categoryCode: "sleep_furniture",
    necessityLevel: "optional",
    timingLabel: "중학생 시기",
    priceMinKrw: 80000,
    priceMaxKrw: 400000,
    reasonText: "장시간 학습 시 바른 자세를 도와주는 선택 준비템이에요.",
    skipReasonText: "기존 의자로 자세에 문제가 없다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 620,
    active: true,
    stageCodes: ["middle_school"]
  }
];

/**
 * 종별 기본 고지 문구. 링크가 `disclosureText`를 비워 두면 items-catalog.service.ts의
 * `defaultDisclosureFor`가 여기서 골라 응답에 실어 주고, 그 값이 앱 구매 CTA 옆에 **그대로**
 * 그려진다(운영은 `PUT /admin/disclosures/:key`로 언제든 갈아끼운다).
 *
 * 라운드 46 Q-4: 그래서 영문으로 두면 안 된다. 종전 값("Purchases through affiliate links
 * may generate a commission for WooriAI.")은 (1) 앱 어디와도 말투가 다른 영문이 사용자
 * 화면에 뜨고(DNC-018 해요체 위반), (2) 모바일의 수수료 고지 판정
 * (src/items/link-marker.ts `statesAffiliateCommission`)이 한국어 어절로 보므로 "고지 없음"
 * 으로 떨어져 한국어 승인 문구가 뒤에 덧붙는 **영문+한국어 이중 고지**가 됐다.
 * 해요체 한국어 + 수령 맥락 어절("수수료를 받")로 적어 한 번만 고지되게 한다(DNC-010).
 */
export const disclosureSeeds: DisclosureSeed[] = [
  {
    key: "affiliate_purchase",
    text: "제휴 링크예요. 구매하시면 우리아이가 수수료를 받을 수 있어요."
  },
  {
    // 스폰서 자체는 광고 사실만 밝힌다 — 수수료를 말하지 않는다. 제휴가 아닌 스폰서 링크에
    // 수수료 문장을 넣으면 받지 않는 돈을 받는다고 적는 셈이다(DNC-010의 반대 방향 오류).
    // 제휴가 섞인 집합에서는 앱이 이 문구 뒤에 수수료 고지를 이어 붙인다(라운드 44 N-2).
    key: "sponsored_product",
    text: "스폰서 광고 상품이에요. 일반 추천과 구분해서 보여드려요."
  },
  {
    // 같은 이유로 한국어 해요체. 의료 자문이 아니라는 사실을 사용자가 읽는 말로 적는다.
    key: "nutrition_supplement",
    text: "영양제·보충제 정보는 참고용이에요. 의학적 조언이 아니니 담당 의료진 안내를 우선해요."
  }
];

// Mirrors apps/mobile/src/categories.ts `categoryCatalog` exactly (id, code, label -> name).
// See MobileCategoryAliasSeed's doc comment for why these live outside categorySeeds.
export const mobileCategoryAliasSeeds: MobileCategoryAliasSeed[] = [
  { id: "c0a7e901-0000-4c01-8c01-c47e900ec001", code: "mobile_diaper_hygiene", name: "기저귀", iconName: "diaper", displayOrder: 1001, selectable: false },
  { id: "c0a7e901-0000-4c02-8c02-c47e900ec002", code: "mobile_feeding_dairy", name: "분유/유제품", iconName: "bottle", displayOrder: 1002, selectable: false },
  { id: "c0a7e901-0000-4c03-8c03-c47e900ec003", code: "mobile_feeding_meal", name: "식비", iconName: "bottle", displayOrder: 1003, selectable: false },
  { id: "c0a7e901-0000-4c04-8c04-c47e900ec004", code: "mobile_clothes_laundry", name: "의류", iconName: "clothes", displayOrder: 1004, selectable: false },
  { id: "c0a7e901-0000-4c05-8c05-c47e900ec005", code: "mobile_outing_mobility", name: "약품/교통", iconName: "stroller", displayOrder: 1005, selectable: false },
  { id: "c0a7e901-0000-4c06-8c06-c47e900ec006", code: "mobile_hospital_checkup", name: "병원/약", iconName: "hospital", displayOrder: 1006, selectable: false },
  { id: "c0a7e901-0000-4c07-8c07-c47e900ec007", code: "mobile_toys_books", name: "교육/도서", iconName: "book", displayOrder: 1007, selectable: false },
  { id: "c0a7e901-0000-4c08-8c08-c47e900ec008", code: "mobile_etc", name: "기타", iconName: "more", displayOrder: 1008, selectable: false }
];

/**
 * `defaultImportCategoryId` in src/onboarding/import-pipeline.service.ts's Excel
 * import stub-row generator (used until real parsing lands) hardcodes this same id
 * for every stub row. Round 4's "categoryId must exist in categories" validation
 * (see requireExistingCategory) means confirming an import job now needs this id to
 * resolve too, or every stub-derived expense would 400 on confirm.
 */
export const importStubCategorySeeds: MobileCategoryAliasSeed[] = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    code: "import_stub_default",
    name: "가져오기 기본",
    iconName: "more",
    displayOrder: 1009,
    selectable: false
  }
];

export const productLinkSeeds: ProductLinkSeed[] = [
  {
    itemTemplateCode: "car_seat",
    platform: "custom",
    title: "개발용 카시트 비교 링크",
    url: "https://example.com/dev/car-seat",
    affiliateUrl: "https://example.com/dev/affiliate/car-seat",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 250000,
    displayOrder: 10,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "stroller",
    platform: "custom",
    title: "개발용 유모차 스폰서 링크",
    url: "https://example.com/dev/stroller-sponsored",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: 320000,
    displayOrder: 20,
    active: true,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "baby_bath",
    platform: "custom",
    title: "개발용 아기 욕조 링크",
    url: "https://example.com/dev/baby-bath",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 25000,
    displayOrder: 30,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "maternity_underwear",
    platform: "custom",
    title: "개발용 임산부 속옷 비교 링크",
    url: "https://example.com/dev/maternity-underwear",
    affiliateUrl: "https://example.com/dev/affiliate/maternity-underwear",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 37500,
    displayOrder: 40,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "anti_nausea_relief",
    platform: "custom",
    title: "개발용 입덧 완화 식품 링크",
    url: "https://example.com/dev/anti-nausea-relief",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 24000,
    displayOrder: 50,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "pregnancy_diary",
    platform: "custom",
    title: "개발용 태교 일기장 스폰서 링크",
    url: "https://example.com/dev/pregnancy-diary",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: 15000,
    displayOrder: 60,
    active: true,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "maternity_clothes",
    platform: "custom",
    title: "개발용 임부복 비교 링크",
    url: "https://example.com/dev/maternity-clothes",
    affiliateUrl: "https://example.com/dev/affiliate/maternity-clothes",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 90000,
    displayOrder: 70,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "body_pillow",
    platform: "custom",
    title: "개발용 임산부 바디필로우 링크",
    url: "https://example.com/dev/body-pillow",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 75000,
    displayOrder: 80,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "stretch_care_cream",
    platform: "custom",
    title: "개발용 튼살 크림 링크",
    url: "https://example.com/dev/stretch-care-cream",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 37500,
    displayOrder: 90,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "iron_supplement",
    platform: "custom",
    title: "개발용 철분제 비교 링크",
    url: "https://example.com/dev/iron-supplement",
    affiliateUrl: "https://example.com/dev/affiliate/iron-supplement",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 25000,
    displayOrder: 100,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "prenatal_class",
    platform: "custom",
    title: "개발용 출산 준비 교실 링크",
    url: "https://example.com/dev/prenatal-class",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 100000,
    displayOrder: 110,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "hospital_bag",
    platform: "custom",
    title: "개발용 출산 가방 준비 링크",
    url: "https://example.com/dev/hospital-bag",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 125000,
    displayOrder: 120,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "newborn_clothes_set",
    platform: "custom",
    title: "개발용 배냇저고리 세트 비교 링크",
    url: "https://example.com/dev/newborn-clothes-set",
    affiliateUrl: "https://example.com/dev/affiliate/newborn-clothes-set",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 50000,
    displayOrder: 130,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "feeding_bottle_set",
    platform: "custom",
    title: "개발용 젖병/소독 세트 링크",
    url: "https://example.com/dev/feeding-bottle-set",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 90000,
    displayOrder: 140,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "breast_pump",
    platform: "custom",
    title: "개발용 유축기 링크",
    url: "https://example.com/dev/breast-pump",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 225000,
    displayOrder: 150,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "nursing_pads",
    platform: "custom",
    title: "개발용 수유 패드/산모 패드 비교 링크",
    url: "https://example.com/dev/nursing-pads",
    affiliateUrl: "https://example.com/dev/affiliate/nursing-pads",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 25000,
    displayOrder: 160,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "crib",
    platform: "custom",
    title: "개발용 아기 침대/요람 링크",
    url: "https://example.com/dev/crib",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 350000,
    displayOrder: 170,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "wipes_bulk",
    platform: "custom",
    title: "개발용 물티슈 대량 구매 스폰서 링크",
    url: "https://example.com/dev/wipes-bulk",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: 37500,
    displayOrder: 180,
    active: true,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "formula",
    platform: "custom",
    title: "개발용 분유 비교 링크",
    url: "https://example.com/dev/formula",
    affiliateUrl: "https://example.com/dev/affiliate/formula",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 72500,
    displayOrder: 190,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "swaddle",
    platform: "custom",
    title: "개발용 속싸개/겉싸개 링크",
    url: "https://example.com/dev/swaddle",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 37500,
    displayOrder: 200,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_thermometer",
    platform: "custom",
    title: "개발용 체온계 링크",
    url: "https://example.com/dev/baby-thermometer",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 47500,
    displayOrder: 210,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_detergent",
    platform: "custom",
    title: "개발용 유아 세제 비교 링크",
    url: "https://example.com/dev/baby-detergent",
    affiliateUrl: "https://example.com/dev/affiliate/baby-detergent",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 19000,
    displayOrder: 220,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "baby_skincare",
    platform: "custom",
    title: "개발용 아기 로션/보습 링크",
    url: "https://example.com/dev/baby-skincare",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 25000,
    displayOrder: 230,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "nail_care_set",
    platform: "custom",
    title: "개발용 아기 손톱 관리 세트 링크",
    url: "https://example.com/dev/nail-care-set",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 12500,
    displayOrder: 240,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_carrier",
    platform: "custom",
    title: "개발용 아기띠 비교 링크",
    url: "https://example.com/dev/baby-carrier",
    affiliateUrl: "https://example.com/dev/affiliate/baby-carrier",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 150000,
    displayOrder: 250,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "mobile_toy",
    platform: "custom",
    title: "개발용 모빌/백색소음기 링크",
    url: "https://example.com/dev/mobile-toy",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 47500,
    displayOrder: 260,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "high_chair",
    platform: "custom",
    title: "개발용 아기 식탁의자 링크",
    url: "https://example.com/dev/high-chair",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 175000,
    displayOrder: 270,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "weaning_tableware",
    platform: "custom",
    title: "개발용 이유식 식기/스푼 비교 링크",
    url: "https://example.com/dev/weaning-tableware",
    affiliateUrl: "https://example.com/dev/affiliate/weaning-tableware",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 30000,
    displayOrder: 280,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "teether",
    platform: "custom",
    title: "개발용 치발기 링크",
    url: "https://example.com/dev/teether",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 15000,
    displayOrder: 290,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "play_mat",
    platform: "custom",
    title: "개발용 놀이매트 링크",
    url: "https://example.com/dev/play-mat",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 175000,
    displayOrder: 300,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "safety_gate",
    platform: "custom",
    title: "개발용 안전문/안전가드 비교 링크",
    url: "https://example.com/dev/safety-gate",
    affiliateUrl: "https://example.com/dev/affiliate/safety-gate",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 90000,
    displayOrder: 310,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "corner_guards",
    platform: "custom",
    title: "개발용 모서리/콘센트 보호 링크",
    url: "https://example.com/dev/corner-guards",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 17500,
    displayOrder: 320,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "push_walker",
    platform: "custom",
    title: "개발용 걸음마 보조 장난감 스폰서 링크",
    url: "https://example.com/dev/push-walker",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: 75000,
    displayOrder: 330,
    active: true,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "first_shoes",
    platform: "custom",
    title: "개발용 첫 걸음마 신발 비교 링크",
    url: "https://example.com/dev/first-shoes",
    affiliateUrl: "https://example.com/dev/affiliate/first-shoes",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 50000,
    displayOrder: 340,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "snack_container",
    platform: "custom",
    title: "개발용 간식 용기/빨대컵 링크",
    url: "https://example.com/dev/snack-container",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 17500,
    displayOrder: 350,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "potty_trainer",
    platform: "custom",
    title: "개발용 유아 변기 링크",
    url: "https://example.com/dev/potty-trainer",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 37500,
    displayOrder: 360,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "toddler_dental",
    platform: "custom",
    title: "개발용 유아 칫솔/치약 비교 링크",
    url: "https://example.com/dev/toddler-dental",
    affiliateUrl: "https://example.com/dev/affiliate/toddler-dental",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 15000,
    displayOrder: 370,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "toddler_tableware",
    platform: "custom",
    title: "개발용 유아 식기 세트 링크",
    url: "https://example.com/dev/toddler-tableware",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 30000,
    displayOrder: 380,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "ride_on_car",
    platform: "custom",
    title: "개발용 붕붕카 링크",
    url: "https://example.com/dev/ride-on-car",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 90000,
    displayOrder: 390,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "sticker_books",
    platform: "custom",
    title: "개발용 스티커북/놀이책 비교 링크",
    url: "https://example.com/dev/sticker-books",
    affiliateUrl: "https://example.com/dev/affiliate/sticker-books",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 34000,
    displayOrder: 400,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "daycare_kit",
    platform: "custom",
    title: "개발용 어린이집 준비물 링크",
    url: "https://example.com/dev/daycare-kit",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 75000,
    displayOrder: 410,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "toddler_rain_gear",
    platform: "custom",
    title: "개발용 유아 우비/장화 링크",
    url: "https://example.com/dev/toddler-rain-gear",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 30000,
    displayOrder: 420,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_scooter",
    platform: "custom",
    title: "개발용 킥보드와 보호장비 비교 링크",
    url: "https://example.com/dev/kids-scooter",
    affiliateUrl: "https://example.com/dev/affiliate/kids-scooter",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 120000,
    displayOrder: 430,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "learning_desk",
    platform: "custom",
    title: "개발용 유아 책상·의자 링크",
    url: "https://example.com/dev/learning-desk",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 240000,
    displayOrder: 440,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "hangul_learning",
    platform: "custom",
    title: "개발용 한글/숫자 교구 링크",
    url: "https://example.com/dev/hangul-learning",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 82500,
    displayOrder: 450,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "art_supplies",
    platform: "custom",
    title: "개발용 미술놀이 세트 비교 링크",
    url: "https://example.com/dev/art-supplies",
    affiliateUrl: "https://example.com/dev/affiliate/art-supplies",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 35000,
    displayOrder: 460,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "kindergarten_kit",
    platform: "custom",
    title: "개발용 유치원 입학 준비물 링크",
    url: "https://example.com/dev/kindergarten-kit",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 125000,
    displayOrder: 470,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_bicycle",
    platform: "custom",
    title: "개발용 네발 자전거와 헬멧 스폰서 링크",
    url: "https://example.com/dev/kids-bicycle",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: 215000,
    displayOrder: 480,
    active: true,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "school_bag",
    platform: "custom",
    title: "개발용 초등 책가방 비교 링크",
    url: "https://example.com/dev/school-bag",
    affiliateUrl: "https://example.com/dev/affiliate/school-bag",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 145000,
    displayOrder: 490,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "school_supplies",
    platform: "custom",
    title: "개발용 학용품 세트 링크",
    url: "https://example.com/dev/school-supplies",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 60000,
    displayOrder: 500,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "study_desk_lamp",
    platform: "custom",
    title: "개발용 학습 책상/스탠드 링크",
    url: "https://example.com/dev/study-desk-lamp",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 300000,
    displayOrder: 510,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_watch_phone",
    platform: "custom",
    title: "개발용 키즈폰/스마트워치 비교 링크",
    url: "https://example.com/dev/kids-watch-phone",
    affiliateUrl: "https://example.com/dev/affiliate/kids-watch-phone",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 175000,
    displayOrder: 520,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "workbook_set",
    platform: "custom",
    title: "개발용 문제집/학습지 링크",
    url: "https://example.com/dev/workbook-set",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 45000,
    displayOrder: 530,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "sports_equipment",
    platform: "custom",
    title: "개발용 운동용품 링크",
    url: "https://example.com/dev/sports-equipment",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 55000,
    displayOrder: 540,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "school_uniform",
    platform: "custom",
    title: "개발용 교복 비교 링크",
    url: "https://example.com/dev/school-uniform",
    affiliateUrl: "https://example.com/dev/affiliate/school-uniform",
    affiliatePartnerCode: null,
    isAffiliate: true,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 325000,
    displayOrder: 550,
    active: true,
    disclosureText: "제휴 링크 예시예요. 구매하시면 수수료가 발생할 수 있어요."
  },
  {
    itemTemplateCode: "study_tablet",
    platform: "custom",
    title: "개발용 인강용 태블릿 링크",
    url: "https://example.com/dev/study-tablet",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 600000,
    displayOrder: 560,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "reference_books",
    platform: "custom",
    title: "개발용 참고서 세트 링크",
    url: "https://example.com/dev/reference-books",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 90000,
    displayOrder: 570,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "ergonomic_chair",
    platform: "custom",
    title: "개발용 학습 의자 링크",
    url: "https://example.com/dev/ergonomic-chair",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: 240000,
    displayOrder: 580,
    active: true,
    disclosureText: null
  }
];
