import type { ChildStageCode } from "@prisma/client";

export type CategorySeed = {
  code: string;
  name: string;
  iconName: string;
  displayOrder: number;
};

export type ItemTemplateSeed = {
  code: string;
  name: string;
  categoryCode: string;
  necessityLevel: "essential" | "convenience" | "optional";
  timingLabel: string;
  priceMinKrw: number | null;
  priceMaxKrw: number | null;
  reasonText: string;
  skipReasonText: string | null;
  usedSecondhandOk: boolean;
  safetyNote: string | null;
  medicalDisclaimerRequired: boolean;
  displayOrder: number;
  active: boolean;
  stageCodes: ChildStageCode[];
};

export type ProductLinkSeed = {
  itemTemplateCode: string;
  platform: "coupang" | "naver" | "custom";
  title: string;
  url: string;
  affiliateUrl: string | null;
  affiliatePartnerCode: string | null;
  isAffiliate: boolean;
  isSponsored: boolean;
  sponsorLabel: string | null;
  priceSnapshotKrw: number | null;
  displayOrder: number;
  active: boolean;
  disclosureText: string | null;
};

export type DisclosureSeed = {
  key: string;
  text: string;
};

export type MobileCategoryAliasSeed = {
  /**
   * Fixed id, matched byte-for-byte against apps/mobile/src/categories.ts'
   * `categoryCatalog` entries. The mobile quick-expense tiles hardcode these UUID
   * literals client-side rather than fetching a canonical id from the server (see
   * that file's comments), so `POST /children/:childId/expenses` from the mobile
   * app always carries one of these exact ids. Round 4 adds server-side validation
   * that `categoryId` must reference an existing `categories` row; without seeding
   * these exact ids too, every mobile-originated expense would 400. These are kept
   * separate from `categorySeeds` (the locked 12) since two mobile tiles
   * intentionally share one taxonomy code ("분유/유제품" and "식비" both map to
   * `feeding_babyfood`), which the unique-per-code canonical list can't represent.
   */
  id: string;
  code: string;
  name: string;
  iconName: string;
  displayOrder: number;
  /**
   * CAT-124: always `false` for these bundles. The rows must keep existing (expenses are
   * already stored under these ids, and the 8-tile quick input + offline resend keep writing
   * them), but they must not be OFFERED as choices — they duplicate the canonical 12 under a
   * different name ("기저귀" vs "기저귀/위생"), which is exactly what a client-side same-name
   * dedupe could not fix. `GET /categories` hides them unless `?includeAll=1`.
   * Migration: prisma/migrations/000018_categories_selectable.
   */
  selectable: false;
};

export const categorySeeds: CategorySeed[] = [
  { code: "pregnancy_mother", name: "임신/산모", iconName: "mother", displayOrder: 10 },
  { code: "hospital_checkup", name: "병원/검사", iconName: "hospital", displayOrder: 20 },
  { code: "birth_postpartum", name: "출산/조리원", iconName: "birth", displayOrder: 30 },
  { code: "diaper_hygiene", name: "기저귀/위생", iconName: "diaper", displayOrder: 40 },
  { code: "feeding_babyfood", name: "수유/이유식", iconName: "bottle", displayOrder: 50 },
  { code: "clothes_laundry", name: "의류/세탁", iconName: "clothes", displayOrder: 60 },
  { code: "sleep_furniture", name: "수면/가구", iconName: "bed", displayOrder: 70 },
  { code: "outing_mobility", name: "외출/이동", iconName: "stroller", displayOrder: 80 },
  { code: "toys_books", name: "장난감/책", iconName: "book", displayOrder: 90 },
  { code: "care_education", name: "돌봄/교육", iconName: "education", displayOrder: 100 },
  { code: "insurance_savings", name: "보험/저축", iconName: "shield", displayOrder: 110 },
  { code: "etc", name: "기타", iconName: "more", displayOrder: 999 }
];

export const itemTemplateSeeds: ItemTemplateSeed[] = [
  {
    code: "pregnancy_vitamin",
    name: "임산부 영양제",
    categoryCode: "pregnancy_mother",
    necessityLevel: "essential",
    timingLabel: "임신 초기부터",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "산모가 매달 챙기는 지출을 아이 준비 기록과 함께 남길 수 있어요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "복용 여부와 종류는 담당 의료진 안내를 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 10,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "car_seat",
    name: "카시트",
    categoryCode: "outing_mobility",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 150000,
    priceMaxKrw: 700000,
    reasonText: "차량 이동이 있다면 퇴원과 외출 전에 안전 준비 상태를 확인해야 해요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "안전 인증과 설치 상태를 확인하고 사고 이력이 있는 중고 제품은 피해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 20,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "diaper_stock",
    name: "기저귀 첫 준비",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "출산 직전~0개월",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "출산 직후 반복 구매가 시작되는 기본 소모품이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 30,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "baby_bath",
    name: "아기 욕조",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "초기 목욕 시간을 안정적으로 만들 수 있는 편의 준비템이에요.",
    skipReasonText: "세면대나 큰 대야를 안전하게 쓸 수 있다면 바로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "물 사용 중에는 아이 곁을 떠나지 않아요.",
    medicalDisclaimerRequired: false,
    displayOrder: 40,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3", "infant_4_6"]
  },
  {
    code: "stroller",
    name: "유모차",
    categoryCode: "outing_mobility",
    necessityLevel: "optional",
    timingLabel: "외출이 늘어날 때",
    priceMinKrw: 100000,
    priceMaxKrw: 1200000,
    reasonText: "생활 반경과 이동 방식에 따라 외출 부담을 줄여주는 선택 준비템이에요.",
    skipReasonText: "차량 이동이 적거나 아기띠로 충분한 시기라면 구매를 늦춰도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "프레임 잠금, 브레이크, 안전벨트 상태를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 50,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "baby_food_maker",
    name: "이유식 조리 도구",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "4~6개월 전후",
    priceMinKrw: 20000,
    priceMaxKrw: 200000,
    reasonText: "이유식 시작 시 조리와 보관 흐름을 편하게 만드는 준비템이에요.",
    skipReasonText: "집에 있는 조리 도구와 보관 용기로 충분하면 별도 구매하지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "소독과 세척이 쉬운 구조인지 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 60,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "first_books",
    name: "첫 그림책",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "7~12개월",
    priceMinKrw: 10000,
    priceMaxKrw: 150000,
    reasonText: "놀이와 책 읽기 기록을 남기고 싶을 때 준비할 수 있어요.",
    skipReasonText: "도서관, 물려받은 책, 선물 책이 충분하면 새로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "찢어진 모서리나 작은 부품이 없는지 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 70,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "maternity_underwear",
    name: "임산부 속옷",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "임신 초기~중기",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "체형 변화에 맞춰 편안하게 입을 수 있는 임산부 전용 속옷이에요.",
    skipReasonText: "기존 속옷을 늘려 입거나 여유 있는 제품으로 버틸 수 있다면 바로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 80,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid"]
  },
  {
    code: "anti_nausea_relief",
    name: "입덧 완화 식품",
    categoryCode: "pregnancy_mother",
    necessityLevel: "convenience",
    timingLabel: "임신 초기",
    priceMinKrw: 8000,
    priceMaxKrw: 40000,
    reasonText: "입덧이 심한 시기에 식사를 대신하거나 도와줄 수 있는 완화 식품이에요.",
    skipReasonText: "입덧 증상이 가볍다면 별도로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "증상이 심하면 자가 대처보다 담당 의료진 상담을 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 90,
    active: true,
    stageCodes: ["pregnancy_early"]
  },
  {
    code: "pregnancy_diary",
    name: "태교 일기장",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "임신 초기~중기",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "태교 과정과 감정을 기록하고 싶을 때 준비하는 선택 준비템이에요.",
    skipReasonText: "메모 앱이나 다른 기록 방법으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 100,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid"]
  },
  {
    code: "maternity_clothes",
    name: "임부복",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "배가 불러오는 시기에 활동과 일상을 편하게 만들어주는 필수 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 110,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "body_pillow",
    name: "임산부 바디필로우",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "배가 무거워지는 시기에 수면 자세를 편하게 잡아주는 편의 준비템이에요.",
    skipReasonText: "기존 베개나 쿠션으로 자세가 편하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 120,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "stretch_care_cream",
    name: "튼살 크림",
    categoryCode: "pregnancy_mother",
    necessityLevel: "optional",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "튼살 관리를 원할 때 선택적으로 사용하는 관리 제품이에요.",
    skipReasonText: "피부 관리가 필수는 아니므로 사용하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 130,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "iron_supplement",
    name: "철분제",
    categoryCode: "pregnancy_mother",
    necessityLevel: "essential",
    timingLabel: "임신 초기~후기",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "빈혈 관리를 위해 임신 중 챙기는 필수 영양제예요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "복용 여부와 용량은 담당 의료진 안내를 우선해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 140,
    active: true,
    stageCodes: ["pregnancy_early", "pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "prenatal_class",
    name: "출산 준비 교실",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "임신 중기~후기",
    priceMinKrw: 0,
    priceMaxKrw: 200000,
    reasonText: "출산과 육아를 미리 준비하고 싶을 때 참여하는 선택 교육 프로그램이에요.",
    skipReasonText: "다른 경로로 정보를 충분히 얻고 있다면 참여하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 150,
    active: true,
    stageCodes: ["pregnancy_mid", "pregnancy_late"]
  },
  {
    code: "hospital_bag",
    name: "출산 가방 준비",
    categoryCode: "birth_postpartum",
    necessityLevel: "essential",
    timingLabel: "임신 후기·출산 전",
    priceMinKrw: 50000,
    priceMaxKrw: 200000,
    reasonText: "입원과 퇴원까지 필요한 물품을 미리 챙기는 필수 준비 과정이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 160,
    active: true,
    stageCodes: ["pregnancy_late"]
  },
  {
    code: "newborn_clothes_set",
    name: "배냇저고리 세트",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "신생아가 퇴원 후 바로 입을 수 있는 필수 첫 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 170,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "feeding_bottle_set",
    name: "젖병/소독 세트",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "수유를 시작하기 전 젖병과 소독 도구를 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: "소독 상태를 꾸준히 확인하고 위생을 관리해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 180,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "breast_pump",
    name: "유축기",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 50000,
    priceMaxKrw: 400000,
    reasonText: "직접 수유가 어려운 상황에서 모유를 보관하고 수유를 돕는 편의 준비템이에요.",
    skipReasonText: "직접 수유로 충분하거나 병원·조리원 대여로 해결된다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 190,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "nursing_pads",
    name: "수유 패드/산모 패드",
    categoryCode: "birth_postpartum",
    necessityLevel: "essential",
    timingLabel: "출산 전후",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "출산 후 분비물과 모유 흡수를 관리하는 필수 위생 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 200,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "crib",
    name: "아기 침대/요람",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "출산 전후",
    priceMinKrw: 100000,
    priceMaxKrw: 600000,
    reasonText: "아이가 안전하게 잠들 수 있는 독립된 수면 공간을 마련하는 편의 준비템이에요.",
    skipReasonText: "부모와 함께 자는 방식으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "중고 제품이라면 안전 인증 여부와 부품 파손 여부를 꼭 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 210,
    active: true,
    stageCodes: ["pregnancy_late", "newborn_0_3"]
  },
  {
    code: "wipes_bulk",
    name: "물티슈 대량 구매",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "0~12개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "매일 반복해서 사용하는 필수 소모품이라 미리 대량으로 준비하면 편해요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 220,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "formula",
    name: "분유",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "0~6개월",
    priceMinKrw: 25000,
    priceMaxKrw: 120000,
    reasonText: "모유 수유를 보완하거나 대체할 때 필요한 필수 먹거리예요.",
    skipReasonText: "완전 모유 수유를 하고 있다면 따로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "아이 상태에 따른 분유 선택은 담당 의료진과 상담 후 결정해요.",
    medicalDisclaimerRequired: true,
    displayOrder: 230,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6"]
  },
  {
    code: "swaddle",
    name: "속싸개/겉싸개",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "0~3개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "신생아를 안정적으로 감싸 체온과 안정감을 지켜주는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 240,
    active: true,
    stageCodes: ["newborn_0_3"]
  },
  {
    code: "baby_thermometer",
    name: "체온계",
    categoryCode: "hospital_checkup",
    necessityLevel: "essential",
    timingLabel: "0~24개월",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "발열 여부를 빠르게 확인할 수 있는 필수 건강 관리 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 250,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "baby_detergent",
    name: "유아 세제",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "0~12개월",
    priceMinKrw: 8000,
    priceMaxKrw: 30000,
    reasonText: "아기 피부에 순한 성분으로 세탁을 관리하는 편의 준비템이에요.",
    skipReasonText: "순한 성분의 기존 세제로 충분하면 따로 구매하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 260,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "baby_skincare",
    name: "아기 로션/보습",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "0~24개월",
    priceMinKrw: 10000,
    priceMaxKrw: 40000,
    reasonText: "건조하기 쉬운 아기 피부를 보습하는 편의 준비템이에요.",
    skipReasonText: "피부 상태가 양호하다면 매일 사용하지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 270,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "nail_care_set",
    name: "아기 손톱 관리 세트",
    categoryCode: "diaper_hygiene",
    necessityLevel: "convenience",
    timingLabel: "0~3개월",
    priceMinKrw: 5000,
    priceMaxKrw: 20000,
    reasonText: "빨리 자라는 아기 손톱을 안전하게 정리하는 편의 준비템이에요.",
    skipReasonText: "가위나 다른 도구로 관리가 가능하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "잠든 시간을 활용하고 끝이 뭉툭한 전용 도구를 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 280,
    active: true,
    stageCodes: ["newborn_0_3"]
  },
  {
    code: "baby_carrier",
    name: "아기띠",
    categoryCode: "outing_mobility",
    necessityLevel: "convenience",
    timingLabel: "0~12개월",
    priceMinKrw: 50000,
    priceMaxKrw: 250000,
    reasonText: "두 손이 자유로운 외출과 이동을 돕는 편의 준비템이에요.",
    skipReasonText: "유모차 이동으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "체중 범위와 착용 방법을 확인하고 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 290,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6", "infant_7_12"]
  },
  {
    code: "mobile_toy",
    name: "모빌/백색소음기",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "0~6개월",
    priceMinKrw: 15000,
    priceMaxKrw: 80000,
    reasonText: "시각 자극과 안정적인 수면 환경을 돕는 선택 준비템이에요.",
    skipReasonText: "다른 방법으로 아이가 잘 안정된다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 300,
    active: true,
    stageCodes: ["newborn_0_3", "infant_4_6"]
  },
  {
    code: "high_chair",
    name: "아기 식탁의자",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "이유식과 식사 시간을 안정적으로 만들어주는 편의 준비템이에요.",
    skipReasonText: "안고 먹이거나 다른 좌석으로 대체할 수 있다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "안전벨트와 잠금장치 상태를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 310,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "weaning_tableware",
    name: "이유식 식기/스푼",
    categoryCode: "feeding_babyfood",
    necessityLevel: "essential",
    timingLabel: "4~12개월",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "이유식을 시작할 때 필요한 필수 식사 도구예요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 320,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "teether",
    name: "치발기",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "4~12개월",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "잇몸이 간지러운 시기에 아이를 달래주는 편의 준비템이에요.",
    skipReasonText: "다른 방법으로 아이가 편안해한다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: "입에 넣는 제품이므로 소독 상태를 꾸준히 관리해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 330,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12"]
  },
  {
    code: "play_mat",
    name: "놀이매트",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "바닥 놀이와 안전한 활동 공간을 마련하는 편의 준비템이에요.",
    skipReasonText: "기존 바닥 환경이 안전하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 340,
    active: true,
    stageCodes: ["infant_4_6", "infant_7_12", "toddler_1_3"]
  },
  {
    code: "safety_gate",
    name: "안전문/안전가드",
    categoryCode: "sleep_furniture",
    necessityLevel: "essential",
    timingLabel: "6~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "이동이 활발해지는 시기에 위험 구역을 막아주는 필수 안전 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: "중고 제품이라면 잠금장치와 고정 상태를 꼭 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 350,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "corner_guards",
    name: "모서리/콘센트 보호",
    categoryCode: "sleep_furniture",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 5000,
    priceMaxKrw: 30000,
    reasonText: "기어다니고 걷기 시작하는 시기에 부딪힘을 줄여주는 편의 준비템이에요.",
    skipReasonText: "가구 배치로 위험을 줄일 수 있다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 360,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "push_walker",
    name: "걸음마 보조 장난감",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "6~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "걸음마를 연습하는 시기에 흥미를 더해주는 선택 준비템이에요.",
    skipReasonText: "손을 잡아주거나 다른 방식으로 연습해도 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "바퀴 잠금과 계단 근처 사용 여부를 확인해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 370,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "first_shoes",
    name: "첫 걸음마 신발",
    categoryCode: "clothes_laundry",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 20000,
    priceMaxKrw: 80000,
    reasonText: "걷기 시작하는 시기에 발을 보호해주는 편의 준비템이에요.",
    skipReasonText: "실내 위주 생활이라면 양말이나 실내화로 대체해도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 380,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "snack_container",
    name: "간식 용기/빨대컵",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "6~24개월",
    priceMinKrw: 5000,
    priceMaxKrw: 30000,
    reasonText: "외출 시 간식과 음료를 편리하게 챙길 수 있는 준비템이에요.",
    skipReasonText: "기존 그릇이나 컵으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 390,
    active: true,
    stageCodes: ["infant_7_12", "toddler_1_3"]
  },
  {
    code: "potty_trainer",
    name: "유아 변기",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "12~24개월",
    priceMinKrw: 15000,
    priceMaxKrw: 60000,
    reasonText: "배변 훈련을 시작할 때 필요한 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 400,
    active: true,
    stageCodes: ["toddler_1_3"]
  },
  {
    code: "toddler_dental",
    name: "유아 칫솔/치약",
    categoryCode: "diaper_hygiene",
    necessityLevel: "essential",
    timingLabel: "12개월 이후",
    priceMinKrw: 5000,
    priceMaxKrw: 25000,
    reasonText: "유치가 나기 시작하며 필요한 필수 구강 관리 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 410,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "toddler_tableware",
    name: "유아 식기 세트",
    categoryCode: "feeding_babyfood",
    necessityLevel: "convenience",
    timingLabel: "12개월 이후",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "혼자 먹는 연습을 시작할 때 편리한 식사 준비템이에요.",
    skipReasonText: "기존 식기로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 420,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "ride_on_car",
    name: "붕붕카",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "12~24개월",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "실내외에서 활동적으로 놀 수 있게 해주는 선택 준비템이에요.",
    skipReasonText: "다른 놀이로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 430,
    active: true,
    stageCodes: ["toddler_1_3"]
  },
  {
    code: "sticker_books",
    name: "스티커북/놀이책",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "12개월 이후",
    priceMinKrw: 8000,
    priceMaxKrw: 60000,
    reasonText: "집중력과 소근육 발달을 돕는 편의 놀이 준비템이에요.",
    skipReasonText: "도서관이나 기존 놀이책으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 440,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "daycare_kit",
    name: "어린이집 준비물",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "12개월 이후",
    priceMinKrw: 30000,
    priceMaxKrw: 120000,
    reasonText: "어린이집 등원 시 필요한 개인 물품을 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 450,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "toddler_rain_gear",
    name: "유아 우비/장화",
    categoryCode: "clothes_laundry",
    necessityLevel: "optional",
    timingLabel: "12개월 이후",
    priceMinKrw: 10000,
    priceMaxKrw: 50000,
    reasonText: "비 오는 날 외출과 물놀이를 즐길 수 있게 해주는 선택 준비템이에요.",
    skipReasonText: "비 오는 날 외출이 적다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 460,
    active: true,
    stageCodes: ["toddler_1_3", "kid_4_7"]
  },
  {
    code: "kids_scooter",
    name: "킥보드와 보호장비",
    categoryCode: "outing_mobility",
    necessityLevel: "convenience",
    timingLabel: "4~7세~초등",
    priceMinKrw: 40000,
    priceMaxKrw: 200000,
    reasonText: "야외 활동 범위가 넓어지는 시기에 즐길 수 있는 편의 준비템이에요.",
    skipReasonText: "다른 야외 활동으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "헬멧과 무릎·손목 보호대를 함께 착용하고 안전한 장소에서 사용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 470,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "learning_desk",
    name: "유아 책상·의자",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "4~7세",
    priceMinKrw: 80000,
    priceMaxKrw: 400000,
    reasonText: "앉아서 집중하는 습관을 만들어주는 편의 준비템이에요.",
    skipReasonText: "거실 책상이나 기존 가구로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 480,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "hangul_learning",
    name: "한글/숫자 교구",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "4~7세",
    priceMinKrw: 15000,
    priceMaxKrw: 150000,
    reasonText: "한글과 숫자에 관심을 갖기 시작할 때 활용하는 선택 교육 준비템이에요.",
    skipReasonText: "다른 놀이나 기관 학습으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 490,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "art_supplies",
    name: "미술놀이 세트",
    categoryCode: "toys_books",
    necessityLevel: "convenience",
    timingLabel: "4~7세~초등",
    priceMinKrw: 10000,
    priceMaxKrw: 60000,
    reasonText: "그리기와 만들기 놀이를 즐길 수 있게 해주는 편의 준비템이에요.",
    skipReasonText: "기관에서 재료를 제공한다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 500,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "kindergarten_kit",
    name: "유치원 입학 준비물",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "4~7세",
    priceMinKrw: 50000,
    priceMaxKrw: 200000,
    reasonText: "유치원 입학 시 필요한 개인 물품을 갖추는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 510,
    active: true,
    stageCodes: ["kid_4_7"]
  },
  {
    code: "kids_bicycle",
    name: "네발 자전거와 헬멧",
    categoryCode: "outing_mobility",
    necessityLevel: "optional",
    timingLabel: "4~7세~초등",
    priceMinKrw: 80000,
    priceMaxKrw: 350000,
    reasonText: "자전거 타기를 배우기 시작할 때 활용하는 선택 준비템이에요.",
    skipReasonText: "아직 관심이 없거나 다른 놀이로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: "헬멧은 머리 크기에 맞는 제품을 새로 준비하고 반드시 착용해요.",
    medicalDisclaimerRequired: false,
    displayOrder: 520,
    active: true,
    stageCodes: ["kid_4_7", "elementary"]
  },
  {
    code: "school_bag",
    name: "초등 책가방",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "초등학생 시기",
    priceMinKrw: 40000,
    priceMaxKrw: 250000,
    reasonText: "초등학교 입학과 함께 매일 사용하는 필수 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 530,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "school_supplies",
    name: "학용품 세트",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "초등학생 시기",
    priceMinKrw: 20000,
    priceMaxKrw: 100000,
    reasonText: "학교 수업에 필요한 필수 학용품을 갖추는 준비템이에요.",
    skipReasonText: null,
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 540,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "study_desk_lamp",
    name: "학습 책상/스탠드",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "초등~중등",
    priceMinKrw: 100000,
    priceMaxKrw: 500000,
    reasonText: "본격적인 학습 습관을 만들어주는 편의 준비템이에요.",
    skipReasonText: "기존 책상과 조명으로 충분하면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 550,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "kids_watch_phone",
    name: "키즈폰/스마트워치",
    categoryCode: "etc",
    necessityLevel: "convenience",
    timingLabel: "초등학생 시기",
    priceMinKrw: 50000,
    priceMaxKrw: 300000,
    reasonText: "등하교 안전과 연락을 위해 준비하는 편의 준비템이에요.",
    skipReasonText: "다른 연락 수단으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 560,
    active: true,
    stageCodes: ["elementary"]
  },
  {
    code: "workbook_set",
    name: "문제집/학습지",
    categoryCode: "care_education",
    necessityLevel: "optional",
    timingLabel: "초등~중등",
    priceMinKrw: 10000,
    priceMaxKrw: 80000,
    reasonText: "학습 내용을 복습하고 보충하고 싶을 때 활용하는 선택 준비템이에요.",
    skipReasonText: "학교 학습만으로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 570,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "sports_equipment",
    name: "운동용품",
    categoryCode: "toys_books",
    necessityLevel: "optional",
    timingLabel: "초등~중등",
    priceMinKrw: 10000,
    priceMaxKrw: 100000,
    reasonText: "체육 활동이나 취미 운동을 시작할 때 활용하는 선택 준비템이에요.",
    skipReasonText: "학교 비품이나 기존 장비로 충분하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 580,
    active: true,
    stageCodes: ["elementary", "middle_school"]
  },
  {
    code: "school_uniform",
    name: "교복",
    categoryCode: "clothes_laundry",
    necessityLevel: "essential",
    timingLabel: "중학생 시기",
    priceMinKrw: 150000,
    priceMaxKrw: 500000,
    reasonText: "중학교 입학과 함께 필수로 갖춰야 하는 의류예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 590,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "study_tablet",
    name: "인강용 태블릿",
    categoryCode: "care_education",
    necessityLevel: "convenience",
    timingLabel: "중학생 시기",
    priceMinKrw: 300000,
    priceMaxKrw: 900000,
    reasonText: "온라인 강의 수강 환경을 갖추는 편의 준비템이에요.",
    skipReasonText: "기존 컴퓨터나 다른 기기로 수강이 가능하다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: false,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 600,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "reference_books",
    name: "참고서 세트",
    categoryCode: "care_education",
    necessityLevel: "essential",
    timingLabel: "중학생 시기",
    priceMinKrw: 30000,
    priceMaxKrw: 150000,
    reasonText: "교과 학습을 보충하기 위한 필수 참고서예요.",
    skipReasonText: null,
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 610,
    active: true,
    stageCodes: ["middle_school"]
  },
  {
    code: "ergonomic_chair",
    name: "학습 의자",
    categoryCode: "sleep_furniture",
    necessityLevel: "optional",
    timingLabel: "중학생 시기",
    priceMinKrw: 80000,
    priceMaxKrw: 400000,
    reasonText: "장시간 학습 시 바른 자세를 도와주는 선택 준비템이에요.",
    skipReasonText: "기존 의자로 자세에 문제가 없다면 따로 사지 않아도 돼요.",
    usedSecondhandOk: true,
    safetyNote: null,
    medicalDisclaimerRequired: false,
    displayOrder: 620,
    active: true,
    stageCodes: ["middle_school"]
  }
];

/**
 * 종별 기본 고지 문구. 링크가 `disclosureText`를 비워 두면 items-catalog.service.ts의
 * `defaultDisclosureFor`가 여기서 골라 응답에 실어 주고, 그 값이 앱 구매 CTA 옆에 **그대로**
 * 그려진다(운영은 `PUT /admin/disclosures/:key`로 언제든 갈아끼운다).
 *
 * 라운드 46 Q-4: 그래서 영문으로 두면 안 된다. 종전 값("Purchases through affiliate links
 * may generate a commission for WooriAI.")은 (1) 앱 어디와도 말투가 다른 영문이 사용자
 * 화면에 뜨고(DNC-018 해요체 위반), (2) 모바일의 수수료 고지 판정
 * (src/items/link-marker.ts `statesAffiliateCommission`)이 한국어 어절로 보므로 "고지 없음"
 * 으로 떨어져 한국어 승인 문구가 뒤에 덧붙는 **영문+한국어 이중 고지**가 됐다.
 * 해요체 한국어 + 수령 맥락 어절("수수료를 받")로 적어 한 번만 고지되게 한다(DNC-010).
 */
export const disclosureSeeds: DisclosureSeed[] = [
  {
    key: "affiliate_purchase",
    text: "제휴 링크예요. 구매하시면 우리아이가 수수료를 받을 수 있어요."
  },
  {
    // 스폰서 자체는 광고 사실만 밝힌다 — 수수료를 말하지 않는다. 제휴가 아닌 스폰서 링크에
    // 수수료 문장을 넣으면 받지 않는 돈을 받는다고 적는 셈이다(DNC-010의 반대 방향 오류).
    // 제휴가 섞인 집합에서는 앱이 이 문구 뒤에 수수료 고지를 이어 붙인다(라운드 44 N-2).
    key: "sponsored_product",
    text: "스폰서 광고 상품이에요. 일반 추천과 구분해서 보여드려요."
  },
  {
    // 같은 이유로 한국어 해요체. 의료 자문이 아니라는 사실을 사용자가 읽는 말로 적는다.
    key: "nutrition_supplement",
    text: "영양제·보충제 정보는 참고용이에요. 의학적 조언이 아니니 담당 의료진 안내를 우선해요."
  }
];

// Mirrors apps/mobile/src/categories.ts `categoryCatalog` exactly (id, code, label -> name).
// See MobileCategoryAliasSeed's doc comment for why these live outside categorySeeds.
export const mobileCategoryAliasSeeds: MobileCategoryAliasSeed[] = [
  { id: "c0a7e901-0000-4c01-8c01-c47e900ec001", code: "mobile_diaper_hygiene", name: "기저귀", iconName: "diaper", displayOrder: 1001, selectable: false },
  { id: "c0a7e901-0000-4c02-8c02-c47e900ec002", code: "mobile_feeding_dairy", name: "분유/유제품", iconName: "bottle", displayOrder: 1002, selectable: false },
  { id: "c0a7e901-0000-4c03-8c03-c47e900ec003", code: "mobile_feeding_meal", name: "식비", iconName: "bottle", displayOrder: 1003, selectable: false },
  { id: "c0a7e901-0000-4c04-8c04-c47e900ec004", code: "mobile_clothes_laundry", name: "의류", iconName: "clothes", displayOrder: 1004, selectable: false },
  { id: "c0a7e901-0000-4c05-8c05-c47e900ec005", code: "mobile_outing_mobility", name: "약품/교통", iconName: "stroller", displayOrder: 1005, selectable: false },
  { id: "c0a7e901-0000-4c06-8c06-c47e900ec006", code: "mobile_hospital_checkup", name: "병원/약", iconName: "hospital", displayOrder: 1006, selectable: false },
  { id: "c0a7e901-0000-4c07-8c07-c47e900ec007", code: "mobile_toys_books", name: "교육/도서", iconName: "book", displayOrder: 1007, selectable: false },
  { id: "c0a7e901-0000-4c08-8c08-c47e900ec008", code: "mobile_etc", name: "기타", iconName: "more", displayOrder: 1008, selectable: false }
];

/**
 * `defaultImportCategoryId` in src/onboarding/import-pipeline.service.ts's Excel
 * import stub-row generator (used until real parsing lands) hardcodes this same id
 * for every stub row. Round 4's "categoryId must exist in categories" validation
 * (see requireExistingCategory) means confirming an import job now needs this id to
 * resolve too, or every stub-derived expense would 400 on confirm.
 */
export const importStubCategorySeeds: MobileCategoryAliasSeed[] = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    code: "import_stub_default",
    name: "가져오기 기본",
    iconName: "more",
    displayOrder: 1009,
    selectable: false
  }
];

/**
 * 출시 트랙 LP-A(2026-09 · 72h 계획 §5 **플랜 B**) — **example.com 플레이스홀더 86곳 전량 교체.**
 *
 * 쿠팡 파트너스 승인 전 출시를 위해 링크 67건 전부를 **일반(비제휴) 쿠팡 검색 링크**
 * (`https://www.coupang.com/np/search?q=<품목명>`)로 바꿨다. 계정·키 없이 동작하는 실 링크라
 * 죽은 CTA(라운드 82 리뷰 M-7 · 확인의 표 #140 ⓕ / #143 ⓖ)가 이 시점에 해소된다.
 *
 *  - **제휴 아님이 곧 정직이다**: 전 행 `isAffiliate: false` · `affiliateUrl: null` ·
 *    `disclosureText: null`(제휴 문구 제거). 검색 링크로는 수수료를 받지 않으므로 제휴 고지가
 *    서면 그것이 허위 고지다(DNC-010의 반대 방향 오류 — disclosureSeeds 주석의 그 규율).
 *  - **스폰서 예시 다섯은 비활성 슬롯로 보존**: 실 스폰서 계약이 없는 출시 시점에 일반 검색
 *    링크가 "스폰서" 배지를 달면 DNC-011의 반대 방향 오류다. 행은 지우지 않고
 *    `active: false`로 내려 두었다(계약 성사 시 실 URL·라벨을 채워 재활성화). `platform`은
 *    `custom`으로 남겨 플랜 A CSV의 (itemTemplate, coupang) 매칭이 일반 링크만 유일하게 잡는다.
 *  - **가격 스냅샷 제거**(`priceSnapshotKrw: null`): 검색 결과 페이지에는 단일 가격이 없다 —
 *    확인할 수 없는 가격을 적어 두면 시드가 그것을 확인 시각과 함께 유효화한다(허위 데이터).
 *  - 추천 점수·정렬은 무변경(DNC-009), `affiliatePartnerCode`는 전 행 `null` 유지(비밀 스캔 계약).
 *
 * **플랜 A 전환**(쿠팡 파트너스 승인 후): `docs/5차/plan-a-affiliate-links-template.csv`를
 * 딥링크로 채워 admin의 CSV 일괄 교체(미리보기→적용)로 무중단 전환한다 — 도구가
 * `isAffiliate: true`와 `affiliateUrl`을 함께 세팅한다(product-link-bulk.service.ts).
 *
 * ⚠️ 시드 upsert는 (itemTemplateId, platform, title)로 기존 행을 찾는다(seed.ts). 이 교체로
 * 세 값이 모두 바뀌었으므로 **기존 dev/test DB에는 재시드 대신 `pnpm db reset`**(또는 test DB
 * 재생성)이 필요하다 — 재시드만 하면 옛 example.com 행이 새 행 옆에 그대로 남는다.
 */
export const productLinkSeeds: ProductLinkSeed[] = [
  {
    itemTemplateCode: "car_seat",
    platform: "coupang",
    title: "카시트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B9%B4%EC%8B%9C%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 10,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "stroller",
    platform: "custom",
    title: "유모차 스폰서 자리 (계약 전 비활성)",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EB%AA%A8%EC%B0%A8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: null,
    displayOrder: 20,
    active: false,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "baby_bath",
    platform: "coupang",
    title: "아기 욕조 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%20%EC%9A%95%EC%A1%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 30,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "maternity_underwear",
    platform: "coupang",
    title: "임산부 속옷 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9E%84%EC%82%B0%EB%B6%80%20%EC%86%8D%EC%98%B7",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 40,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "anti_nausea_relief",
    platform: "coupang",
    title: "입덧 완화 식품 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9E%85%EB%8D%A7%20%EC%99%84%ED%99%94%20%EC%8B%9D%ED%92%88",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 50,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "pregnancy_diary",
    platform: "custom",
    title: "태교 일기장 스폰서 자리 (계약 전 비활성)",
    url: "https://www.coupang.com/np/search?q=%ED%83%9C%EA%B5%90%20%EC%9D%BC%EA%B8%B0%EC%9E%A5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: null,
    displayOrder: 60,
    active: false,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "maternity_clothes",
    platform: "coupang",
    title: "임부복 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9E%84%EB%B6%80%EB%B3%B5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 70,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "body_pillow",
    platform: "coupang",
    title: "임산부 바디필로우 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9E%84%EC%82%B0%EB%B6%80%20%EB%B0%94%EB%94%94%ED%95%84%EB%A1%9C%EC%9A%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 80,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "stretch_care_cream",
    platform: "coupang",
    title: "튼살 크림 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%8A%BC%EC%82%B4%20%ED%81%AC%EB%A6%BC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 90,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "iron_supplement",
    platform: "coupang",
    title: "철분제 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B2%A0%EB%B6%84%EC%A0%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 100,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "prenatal_class",
    platform: "coupang",
    title: "출산 준비 교실 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B6%9C%EC%82%B0%20%EC%A4%80%EB%B9%84%20%EA%B5%90%EC%8B%A4",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 110,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "hospital_bag",
    platform: "coupang",
    title: "출산 가방 준비 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B6%9C%EC%82%B0%20%EA%B0%80%EB%B0%A9%20%EC%A4%80%EB%B9%84",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 120,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "newborn_clothes_set",
    platform: "coupang",
    title: "배냇저고리 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%B0%B0%EB%83%87%EC%A0%80%EA%B3%A0%EB%A6%AC%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 130,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "feeding_bottle_set",
    platform: "coupang",
    title: "젖병/소독 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%A0%96%EB%B3%91%20%EC%86%8C%EB%8F%85%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 140,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "breast_pump",
    platform: "coupang",
    title: "유축기 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%B6%95%EA%B8%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 150,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "nursing_pads",
    platform: "coupang",
    title: "수유 패드/산모 패드 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%88%98%EC%9C%A0%20%ED%8C%A8%EB%93%9C%20%EC%82%B0%EB%AA%A8%20%ED%8C%A8%EB%93%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 160,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "crib",
    platform: "coupang",
    title: "아기 침대/요람 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%20%EC%B9%A8%EB%8C%80%20%EC%9A%94%EB%9E%8C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 170,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "wipes_bulk",
    platform: "custom",
    title: "물티슈 대량 구매 스폰서 자리 (계약 전 비활성)",
    url: "https://www.coupang.com/np/search?q=%EB%AC%BC%ED%8B%B0%EC%8A%88%20%EB%8C%80%EB%9F%89%20%EA%B5%AC%EB%A7%A4",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: null,
    displayOrder: 180,
    active: false,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "formula",
    platform: "coupang",
    title: "분유 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%B6%84%EC%9C%A0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 190,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "swaddle",
    platform: "coupang",
    title: "속싸개/겉싸개 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%86%8D%EC%8B%B8%EA%B0%9C%20%EA%B2%89%EC%8B%B8%EA%B0%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 200,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_thermometer",
    platform: "coupang",
    title: "체온계 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B2%B4%EC%98%A8%EA%B3%84",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 210,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_detergent",
    platform: "coupang",
    title: "유아 세제 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EC%84%B8%EC%A0%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 220,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_skincare",
    platform: "coupang",
    title: "아기 로션/보습 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%20%EB%A1%9C%EC%85%98%20%EB%B3%B4%EC%8A%B5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 230,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "nail_care_set",
    platform: "coupang",
    title: "아기 손톱 관리 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%20%EC%86%90%ED%86%B1%20%EA%B4%80%EB%A6%AC%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 240,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_carrier",
    platform: "coupang",
    title: "아기띠 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%EB%9D%A0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 250,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "mobile_toy",
    platform: "coupang",
    title: "모빌/백색소음기 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%AA%A8%EB%B9%8C%20%EB%B0%B1%EC%83%89%EC%86%8C%EC%9D%8C%EA%B8%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 260,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "high_chair",
    platform: "coupang",
    title: "아기 식탁의자 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%84%EA%B8%B0%20%EC%8B%9D%ED%83%81%EC%9D%98%EC%9E%90",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 270,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "weaning_tableware",
    platform: "coupang",
    title: "이유식 식기/스푼 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9D%B4%EC%9C%A0%EC%8B%9D%20%EC%8B%9D%EA%B8%B0%20%EC%8A%A4%ED%91%BC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 280,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "teether",
    platform: "coupang",
    title: "치발기 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B9%98%EB%B0%9C%EA%B8%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 290,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "play_mat",
    platform: "coupang",
    title: "놀이매트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%86%80%EC%9D%B4%EB%A7%A4%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 300,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "safety_gate",
    platform: "coupang",
    title: "안전문/안전가드 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%95%88%EC%A0%84%EB%AC%B8%20%EC%95%88%EC%A0%84%EA%B0%80%EB%93%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 310,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "corner_guards",
    platform: "coupang",
    title: "모서리/콘센트 보호 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%AA%A8%EC%84%9C%EB%A6%AC%20%EC%BD%98%EC%84%BC%ED%8A%B8%20%EB%B3%B4%ED%98%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 320,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "push_walker",
    platform: "custom",
    title: "걸음마 보조 장난감 스폰서 자리 (계약 전 비활성)",
    url: "https://www.coupang.com/np/search?q=%EA%B1%B8%EC%9D%8C%EB%A7%88%20%EB%B3%B4%EC%A1%B0%20%EC%9E%A5%EB%82%9C%EA%B0%90",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: null,
    displayOrder: 330,
    active: false,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "first_shoes",
    platform: "coupang",
    title: "첫 걸음마 신발 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B2%AB%20%EA%B1%B8%EC%9D%8C%EB%A7%88%20%EC%8B%A0%EB%B0%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 340,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "snack_container",
    platform: "coupang",
    title: "간식 용기/빨대컵 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EA%B0%84%EC%8B%9D%20%EC%9A%A9%EA%B8%B0%20%EB%B9%A8%EB%8C%80%EC%BB%B5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 350,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "potty_trainer",
    platform: "coupang",
    title: "유아 변기 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EB%B3%80%EA%B8%B0",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 360,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "toddler_dental",
    platform: "coupang",
    title: "유아 칫솔/치약 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EC%B9%AB%EC%86%94%20%EC%B9%98%EC%95%BD",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 370,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "toddler_tableware",
    platform: "coupang",
    title: "유아 식기 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EC%8B%9D%EA%B8%B0%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 380,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "ride_on_car",
    platform: "coupang",
    title: "붕붕카 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%B6%95%EB%B6%95%EC%B9%B4",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 390,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "sticker_books",
    platform: "coupang",
    title: "스티커북/놀이책 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%8A%A4%ED%8B%B0%EC%BB%A4%EB%B6%81%20%EB%86%80%EC%9D%B4%EC%B1%85",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 400,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "daycare_kit",
    platform: "coupang",
    title: "어린이집 준비물 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%96%B4%EB%A6%B0%EC%9D%B4%EC%A7%91%20%EC%A4%80%EB%B9%84%EB%AC%BC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 410,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "toddler_rain_gear",
    platform: "coupang",
    title: "유아 우비/장화 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EC%9A%B0%EB%B9%84%20%EC%9E%A5%ED%99%94",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 420,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_scooter",
    platform: "coupang",
    title: "킥보드와 보호장비 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%82%A5%EB%B3%B4%EB%93%9C%EC%99%80%20%EB%B3%B4%ED%98%B8%EC%9E%A5%EB%B9%84",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 430,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "learning_desk",
    platform: "coupang",
    title: "유아 책상·의자 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%95%84%20%EC%B1%85%EC%83%81%20%EC%9D%98%EC%9E%90",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 440,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "hangul_learning",
    platform: "coupang",
    title: "한글/숫자 교구 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%95%9C%EA%B8%80%20%EC%88%AB%EC%9E%90%20%EA%B5%90%EA%B5%AC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 450,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "art_supplies",
    platform: "coupang",
    title: "미술놀이 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%AF%B8%EC%88%A0%EB%86%80%EC%9D%B4%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 460,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kindergarten_kit",
    platform: "coupang",
    title: "유치원 입학 준비물 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EC%B9%98%EC%9B%90%20%EC%9E%85%ED%95%99%20%EC%A4%80%EB%B9%84%EB%AC%BC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 470,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_bicycle",
    platform: "custom",
    title: "네발 자전거와 헬멧 스폰서 자리 (계약 전 비활성)",
    url: "https://www.coupang.com/np/search?q=%EB%84%A4%EB%B0%9C%20%EC%9E%90%EC%A0%84%EA%B1%B0%EC%99%80%20%ED%97%AC%EB%A9%A7",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: true,
    sponsorLabel: "스폰서 예시",
    priceSnapshotKrw: null,
    displayOrder: 480,
    active: false,
    disclosureText: "스폰서 상품 예시예요."
  },
  {
    itemTemplateCode: "school_bag",
    platform: "coupang",
    title: "초등 책가방 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B4%88%EB%93%B1%20%EC%B1%85%EA%B0%80%EB%B0%A9",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 490,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "school_supplies",
    platform: "coupang",
    title: "학용품 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%95%99%EC%9A%A9%ED%92%88%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 500,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "study_desk_lamp",
    platform: "coupang",
    title: "학습 책상/스탠드 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%95%99%EC%8A%B5%20%EC%B1%85%EC%83%81%20%EC%8A%A4%ED%83%A0%EB%93%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 510,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_watch_phone",
    platform: "coupang",
    title: "키즈폰/스마트워치 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%82%A4%EC%A6%88%ED%8F%B0%20%EC%8A%A4%EB%A7%88%ED%8A%B8%EC%9B%8C%EC%B9%98",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 520,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "workbook_set",
    platform: "coupang",
    title: "문제집/학습지 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%AC%B8%EC%A0%9C%EC%A7%91%20%ED%95%99%EC%8A%B5%EC%A7%80",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 530,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "sports_equipment",
    platform: "coupang",
    title: "운동용품 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9A%B4%EB%8F%99%EC%9A%A9%ED%92%88",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 540,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "school_uniform",
    platform: "coupang",
    title: "교복 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EA%B5%90%EB%B3%B5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 550,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "study_tablet",
    platform: "coupang",
    title: "인강용 태블릿 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9D%B8%EA%B0%95%EC%9A%A9%20%ED%83%9C%EB%B8%94%EB%A6%BF",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 560,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "reference_books",
    platform: "coupang",
    title: "참고서 세트 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B0%B8%EA%B3%A0%EC%84%9C%20%EC%84%B8%ED%8A%B8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 570,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "ergonomic_chair",
    platform: "coupang",
    title: "학습 의자 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%95%99%EC%8A%B5%20%EC%9D%98%EC%9E%90",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 580,
    active: true,
    disclosureText: null
  },
  // 라운드 82 트랙 B — 링크 0건으로 남아 있던 넷. 이 넷 중 둘(`pregnancy_vitamin`·
  // `diaper_stock`)은 `essential`이고 도메인 점수로 재면 자기 시기 "지금 필요" 목록의 머리에
  // 서므로, 온보딩을 막 마친 사용자에게 앱이 처음 내미는 추천 카드가 구매 경로 0건이었다
  // (핵심 루프 4단계가 1순위에서 시작되지 않았다 — apps/api/test/seed-data.test.ts의 대장 참고).
  //
  // ⚠️ 넷 다 **일반 링크**다: `isAffiliate: false` · `isSponsored: false` · `sponsorLabel: null` ·
  // `disclosureText: null`. 고지 판정은 **링크 집합**에서 나오므로(apps/mobile/src/items/link-marker.ts —
  // 라운드 43 M-1/M-2) 이 넷은 DNC-010 문장도 DNC-011 배지도 한 줄 늘리지 않는다.
  // ⚠️ 제목에 효능·효과를 적지 않는다(DNC-020) — 위 `iron_supplement`의 중립 제목이 본보기다.
  {
    itemTemplateCode: "pregnancy_vitamin",
    platform: "coupang",
    title: "임산부 영양제 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9E%84%EC%82%B0%EB%B6%80%20%EC%98%81%EC%96%91%EC%A0%9C",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 590,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "diaper_stock",
    platform: "coupang",
    title: "기저귀 첫 준비 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EA%B8%B0%EC%A0%80%EA%B7%80%20%EC%B2%AB%20%EC%A4%80%EB%B9%84",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 600,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "baby_food_maker",
    platform: "coupang",
    title: "이유식 조리 도구 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9D%B4%EC%9C%A0%EC%8B%9D%20%EC%A1%B0%EB%A6%AC%20%EB%8F%84%EA%B5%AC",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 610,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "first_books",
    platform: "coupang",
    title: "첫 그림책 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%B2%AB%20%EA%B7%B8%EB%A6%BC%EC%B1%85",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 620,
    active: true,
    disclosureText: null
  },
  /* -------------------------------------------------- 라운드 83 트랙 A: 일반 링크 다섯
   *
   * 고치는 문제: 아래 다섯 품목은 **유일한 링크가 스폰서**였다. 상세 화면의 강조 판정은
   * "링크가 있는가"가 아니라 "비스폰서 링크가 있는가"다 —
   * `apps/mobile/src/items/link-marker.ts`의 `primaryPurchaseLinkIndex`가
   * `links.findIndex((link) => !link.isSponsored)`이고, 전부 스폰서면 **-1**이다. 그 -1이
   * 판매처 행의 채움(`filledPurchaseRowIndex`)과 전폭 CTA(`primaryPurchaseLink`)를 **동시에**
   * 끄므로, 그 다섯 화면에는 외곽선 "구매" 행 하나만 서고 이 앱이 핵심 루프 4단계(구매 링크
   * 클릭)를 여는 **유일한 큰 버튼**이 아예 렌더되지 않았다. 그중 `wipes_bulk`는 카탈로그가
   * 스스로 `essential`이라고 부르는 품목이다.
   *
   * ⚠️ 라운드 82 B가 세운 계약("링크 ≥1" · 링크 0건 대장)은 이 자리를 묻지 않는다 —
   * 그 계약은 링크의 **개수**를 세고 화면은 링크의 **종별**을 본다. 그래서 다섯 품목이
   * 그 사이에 있었고 계약은 초록이었다. `apps/api/test/seed-data.test.ts`의
   * `ITEM_CODES_WITHOUT_NON_SPONSORED_LINK` 대장이 오늘부터 화면과 같은 술어로 묻는다.
   *
   * 모양은 당시 카탈로그의 38건이 쓰던 **일반 링크** 그대로였다(`platform: "custom"` ·
   * `example.com` dev 플레이스홀더 · `isAffiliate: false` · `isSponsored: false` ·
   * `sponsorLabel: null` · `disclosureText: null` · `active: true`).
   * ⚠️ **두 시점**: 그 뒤 출시 트랙 LP-A(플랜 B)가 배열 전체를 실 쿠팡 검색 링크로
   * 교체했다 — 오늘의 모양은 배열 머리의 플랜 B 주석이 단일 소스다.
   * ⚠️ 일반 링크에는 고지할 대상 자체가 없으므로 **DNC-010 문장도 DNC-011 배지도 늘지 않는다**
   * (`link-marker.ts`가 문구를 링크 **집합**으로 정한다 — 스폰서 링크는 그 집합에 그대로 남아
   * 배지와 캡션을 계속 단다). 제목에는 효능·효과를 적지 않는다(DNC-020).
   * ⚠️ 정렬·점수는 한 글자도 건드리지 않는다(DNC-009) — `displayOrder`는 스폰서 링크보다
   * 뒤이고, 강조가 앞줄이 아니라 **첫 비스폰서 줄**로 가는 것은 라운드 64 #1이 세운 판정이다.
   */
  {
    itemTemplateCode: "wipes_bulk",
    platform: "coupang",
    title: "물티슈 대량 구매 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%AC%BC%ED%8B%B0%EC%8A%88%20%EB%8C%80%EB%9F%89%20%EA%B5%AC%EB%A7%A4",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 630,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "stroller",
    platform: "coupang",
    title: "유모차 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EC%9C%A0%EB%AA%A8%EC%B0%A8",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 640,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "pregnancy_diary",
    platform: "coupang",
    title: "태교 일기장 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%ED%83%9C%EA%B5%90%20%EC%9D%BC%EA%B8%B0%EC%9E%A5",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 650,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "push_walker",
    platform: "coupang",
    title: "걸음마 보조 장난감 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EA%B1%B8%EC%9D%8C%EB%A7%88%20%EB%B3%B4%EC%A1%B0%20%EC%9E%A5%EB%82%9C%EA%B0%90",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 660,
    active: true,
    disclosureText: null
  },
  {
    itemTemplateCode: "kids_bicycle",
    platform: "coupang",
    title: "네발 자전거와 헬멧 쿠팡 검색",
    url: "https://www.coupang.com/np/search?q=%EB%84%A4%EB%B0%9C%20%EC%9E%90%EC%A0%84%EA%B1%B0%EC%99%80%20%ED%97%AC%EB%A9%A7",
    affiliateUrl: null,
    affiliatePartnerCode: null,
    isAffiliate: false,
    isSponsored: false,
    sponsorLabel: null,
    priceSnapshotKrw: null,
    displayOrder: 670,
    active: true,
    disclosureText: null
  }
];
