import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const sourcePath = "docs/3차/db_api/wooriai_phase3_openapi_v0_3.yaml";
const outputPath = "packages/contracts/src/openapi.generated.ts";

if (!existsSync(sourcePath)) {
  console.error(`[contracts] OpenAPI source not found: ${sourcePath}`);
  process.exit(1);
}

const source = readFileSync(sourcePath, "utf8");
const sourceSha256 = createHash("sha256").update(source).digest("hex");
const openapiVersion = source.match(/^openapi:\s*['\"]?([^'\"\s]+)['\"]?/m)?.[1];
if (!openapiVersion) {
  throw new Error("OpenAPI version is missing from the source contract.");
}

const paths = [...source.matchAll(/^\s{2}(\/[^:]+):\s*$/gm)].map((match) => match[1]).sort();
if (paths.length === 0) {
  throw new Error("OpenAPI source contains no paths.");
}

const generated = `// Generated by scripts/generate-openapi-types.ts. Do not edit by hand.\n` +
  `export const OPENAPI_CONTRACT = ${JSON.stringify(
    {
      source: sourcePath.replaceAll("\\", "/"),
      sourceSha256,
      openapiVersion,
      pathCount: paths.length,
      paths
    },
    null,
    2
  )} as const;\n`;

writeFileSync(resolve(outputPath), generated, "utf8");
console.log(`[contracts] generated ${outputPath} (${paths.length} paths, sha256=${sourceSha256})`);
